### ISSUE TITLE
Wrong documentation.

### ISSUE THREAD

**Issue by theCodingDJ** [pichillilorenzo/inappwebview.dev#9]
Just a quick note: 
[Here](https://github.com/pichillilorenzo/inappwebview.dev/tree/main/versioned_docs/version-5.x.x/debugging-webviews.md) the documentation states that debugging cannot be enabled or disabled. However, as of iOS 16.4 the debugging is disabled by default and can be enabled via the following property:
https://developer.apple.com/documentation/webkit/wkwebview/4111163-isinspectable

**Comment by pichillilorenzo** [comment]
That's the old version 5 of the plugin.
Use the latest one: https://inappwebview.dev/docs/debugging-webviews#inspect-ios-and-macos-webviews
